### ISSUE TITLE
Difference to jerryscript - or: what is escargot?

### ISSUE THREAD

**Issue by wille-io** [pando-project/escargot#94]
What are the differences between escargot and jerryscript?
What is escargot exactly?

**Comment by zherczeg** [comment]
Escargot is an EcmaScript engine for mid-range devices, i.e. you have a few MBytes of memory for each JS instance. JerryScript is an EcmaScript engine for low-end devices, with 64K or less memory. So in Escargot you have much more freedom to implement features and performance optimizations because the memory constraints are less tight.

**Comment by wille-io** [comment]
Perfect, exactly what I need.
Thanks.
